//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: frelagn
// Function header: frelagnFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createfrelagnFunctionMap();

extern "C"  {


	xsf77Call    relagn_;
}


#endif
