//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: frelagn
// Function body: frelagnFunctionMap.cxx

#include    "frelagnFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>

void 
createfrelagnFunctionMap()
{


	XSFunctionMap["relagn"]   = new XSCall<xsf77Call>(relagn_);

}
