//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: frelagn Created :
// Initializer: frelagn.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "frelagnFunctionMap.h"
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Frelagn_Init(Tcl_Interp* tclInterp);
extern "C" int Frelagn_SafeInit(Tcl_Interp* tclInterp);

int Frelagn_Init(Tcl_Interp* tclInterp)
{
        return Frelagn_SafeInit(tclInterp);
}

int Frelagn_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "frelagn";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createfrelagnFunctionMap();
        XSModelFunction::updateComponentList
              ("/home/wljw75/Documents/phd/RELAGN/src/fortran_version/frelagn.dat");
        return TCL_OK;

}

