//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: relagn Created :
// Initializer: relagn.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "relagnFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Relagn_Init(Tcl_Interp* tclInterp);
extern "C" int Relagn_SafeInit(Tcl_Interp* tclInterp);

int Relagn_Init(Tcl_Interp* tclInterp)
{
        return Relagn_SafeInit(tclInterp);
}

int Relagn_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "relagn";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/astro-guest/Documents/phd/model_codes/RELAGN/src/fortran_version/lmod_relagn.dat");
        createrelagnFunctionMap();
        return TCL_OK;

}

