//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: relagn
// Function body: relagnFunctionMap.cxx

#include    "relagnFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>

void 
createrelagnFunctionMap()
{


	XSFunctionMap["relagn"]   = new XSCall<xsf77Call>(relagn_);

}
