//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: relagn
// Function body: relagnFunctionMap.cxx

#include    "relagnFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createrelagnFunctionMap()
{


	XSModelFunction::addFunctionPointer( "relagn",     new XSCall<xsf77Call>(relagn_) );

}
